### PR TITLE
List menu

### PR DESCRIPTION
**Pull request by Juan-Garcia1**
User can open list menu to delete list

### CODE REVIEW

**Comment by clockwerkz** [comment]
Looking good - two suggestions:

Right now if the list is open I have to close it with the x; I can't close it by clicking on the ellipsis again. That's a pretty simple fix: in openListMenu just setState equal to the opposite of listMenuOpen, like did you did with the toggleTitle. (might want to change this function to toggleListMenu for semantics). 

The second is a bit more complicated: I was wondering if we could have the list menu open to the right of the list. The difficulty in this is if the List happens to be on the right, in which case the list menu should just open on top of the list. That would require some sort of calculation on where the list is and then offset the list menu. If it can be done, awesome. If not, no worries. 

Thanks for the PR!

**Comment by nroode** [comment]
Agree with Carlos!

If the calculation/list menu placement when on the right side of the screen is too difficult... I think it would look fine if every list menu was placed directly under the ellipsis (and to the right of the list, like trello) each time, even if the right one bled off-screen.

**Comment by clockwerkz** [comment]
Ahh yeah, what Natalie said. :D I had little sleep last night!

**Comment by Juan-Garcia1** [comment]
- User can toggle list menu by clicking on ellipsis.
- Positioned List Menu to the right

**Pull request merged**
