### PR TITLE
Feature/copy list function

### PR DESCRIPTION
**Pull request by clockwerkz**
Adds Copy List to the List Menu. Selecting Copy List will change the Menu to show the Copy List dialogue, with a textarea set to the current list's title and a Create List button.Clicking it will create a copy of the list,  together with a copy of the cards, in a new list and put it right after the current list in list order.

### CODE REVIEW

**Comment by nroode** [comment]
Looks good!  Agree that the only thing I see that could be fixed is how the list title isn't entered already once the list is copied (similar to it not being saved with local storage).

**Comment by clockwerkz** [comment]
Ok! So this latest commit resolves the issue with the List Components names editable by default. I went ahead and made a change so that if the list's title is blank, the edit value is true. This way, when you click to create a new list, it will open the input dialogue for the list's title. Otherwise, it will just display the title. So when you click to copy a List, the list copy will not display the input dialogue for the title. 
The other change I made in here is getting rid of the delete button (X) from the Cards displayed in the list, so that the only way now to the delete the card is through it's modal.

**Comment by nroode** [comment]
Yay! This update makes me happy.

The only other small thing - and I don't recall if it was always like this or just changed now - is that when Adding a new list the default button says 'Edit List' on it instead of 'Add List'.

**Comment by clockwerkz** [comment]
Yep, you're right. Nice catch. :) I think I fixed it now.

**Pull request merged**
